<a href="https://colab.research.google.com/github/alina-bogdanovskaya/Linear_Algebra_Feb2022/blob/lesson4/Linear_equations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy import linalg

##__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

$x_{4} = c\\
-2x_{3} + 3c = 4\\
x_{3} = \frac{3c}{2} - 2\\
-x_{2} + \frac{3c}{2} - 2 + 5c = -2\\
x_{2} = \frac{13}{2}c\\
x_{1} + \frac{13}{2}c - \frac{3c}{2} + 2 - 2c\\
x_{1} = -3c - 2
$

##__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [2]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([[4, -17, 0]])
c = np.concatenate((a, b.T), axis=1)
c


array([[  3,  -1,   1,   4],
       [  2,  -5,  -3, -17],
       [  1,   1,  -1,   0]])

In [3]:
rank_a = np.linalg.matrix_rank(a)
rank_c = np.linalg.matrix_rank(c)
print(rank_a, rank_c)

3 3


In [4]:
np.linalg.solve(a,b.T)

array([[1.],
       [2.],
       [3.]])

a) Система совместна и имеет единственное решение.

In [5]:
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([[1, -2, 5]])
c = np.concatenate((a, b.T), axis=1)
c


array([[ 2, -4,  6,  1],
       [ 1, -2,  3, -2],
       [ 3, -6,  9,  5]])

In [6]:
rank_a = np.linalg.matrix_rank(a)
rank_c = np.linalg.matrix_rank(c)
print(rank_a, rank_c)

1 2


б) Система несовместна.

In [7]:
a = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([[4, -2]])
c = np.concatenate((a, b.T), axis=1)
c


array([[ 1,  2,  5,  4],
       [ 3,  1, -8, -2]])

In [8]:
rank_a = np.linalg.matrix_rank(a)
rank_c = np.linalg.matrix_rank(c)
print(rank_a, rank_c)

2 2


в) Система совместна и имеет бесконечное количество решений.

##__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [9]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([[3, 2, 4, 1]])
c = np.concatenate((a, b.T), axis=1)
c


array([[ 1,  3, -2,  4,  3],
       [ 0,  5,  0,  1,  2],
       [ 0,  0,  3,  0,  4],
       [ 0,  0,  0,  2,  1]])

In [10]:
rank_a = np.linalg.matrix_rank(a)
rank_c = np.linalg.matrix_rank(c)
print(rank_a, rank_c)

4 4


In [11]:
np.linalg.solve(a,b.T)

array([[2.76666667],
       [0.3       ],
       [1.33333333],
       [0.5       ]])

Система совместна и имеет единственное решение.

##__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

##Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a
\end{matrix}
\end{pmatrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c + a - 2b
\end{matrix}
\end{pmatrix}$

Ранг матрицы $A$ = 2. Система будет несовместной в случае, если ранг расширенной матрицы больше 2, т.е.<br>
$c + a - 2b \neq 0$



In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 1]])
c = np.concatenate((a, b.T), axis=1)
c


array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 1]])

In [13]:
rank_a = np.linalg.matrix_rank(a)
rank_c = np.linalg.matrix_rank(c)
print(rank_a, rank_c)

2 3


##__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


а)<br>
$detA = 
\begin{vmatrix}
1 & -2\\
3 & -4
\end{vmatrix}=
-4 + 6 = 2 \neq 0$

Система совместна.

$detA_{1} =
\begin{vmatrix}
1 & -2\\
7 & -4
\end{vmatrix} = 
-4 + 14 = 10$

$detA_{2} =
\begin{vmatrix}
1 & 1\\
3 & 7
\end{vmatrix} = 
7 - 3 = 4$

$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2} = 5,$

$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2} = 2.$


In [14]:
a = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]])
np.linalg.solve(a, b.T)

array([[5.],
       [2.]])

б)<br> 
$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}-
\begin{vmatrix}
-1 & 5\\ 
4 & 1 
\end{vmatrix}+
2\begin{vmatrix}
-1 & 5 \\ 
1 & -3
\end{vmatrix}=
2(1 + 12) - (-1 - 20) + 2(3 - 5) = 26 + 21 - 4 = 43\neq 0$

Cистема совместна.

$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
\begin{vmatrix}
-1 & 5\\ 
1 & -3 
\end{vmatrix}-
4\begin{vmatrix}
10 & 5\\ 
-2 & -3 
\end{vmatrix}+
\begin{vmatrix}
10 & -1 \\ 
-2 & 1
\end{vmatrix}= 
(3 - 5) - 4(-30 + 10) + (10 - 2) = -2 + 80 + 8 = 86$

$detA_{2}=\begin{vmatrix}
2 & 10 & -5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
2\begin{vmatrix}
10 & 5\\ 
-2 & -3 
\end{vmatrix}-
\begin{vmatrix}
2 & 5\\ 
1 & -3 
\end{vmatrix}+
\begin{vmatrix}
2 & 10 \\ 
1 & -2
\end{vmatrix}= 
2(-30 + 10) - (-6 - 5) + (-4 - 10) = -40 + 11 - 14 = -43$

$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
-\begin{vmatrix}
-1 & 10\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
2 & 10\\ 
2 & 1 
\end{vmatrix}+
2\begin{vmatrix}
2 & -1 \\ 
2 & 4
\end{vmatrix}= 
-(-1 - 40) + (2 - 20) + 2(8 + 2) = 41 - 18 + 20 = 43$

$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43} = 2,$

$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43} = -1,$

$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}= 1.$


In [15]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -2, 1]])
np.linalg.solve(a, b.T)

array([[ 2.],
       [-1.],
       [ 1.]])

In [16]:
det_a = np.linalg.det(a).round(0)
det_a

43.0

In [17]:
a_1 = np.insert(np.delete(a,0,1), 0, b, 1)
det_a_1 = np.linalg.det(a_1).round(0)
det_a_1

86.0

In [18]:
a_2 = np.insert(np.delete(a,1,1), 1, b, 1)
det_a_2 = np.linalg.det(a_2).round(0)
det_a_2

-43.0

In [19]:
a_3 = np.insert(np.delete(a,2,1), 2, b, 1)
det_a_3 = np.linalg.det(a_3).round(0)
det_a_3

43.0

In [22]:
print(f'x1 = {det_a_1/det_a};\nx2 = {det_a_2/det_a};\nx3 = {det_a_3/det_a}.')

x1 = 2.0;
x2 = -1.0;
x3 = 1.0.


##__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [23]:
def LU_decomp(x):
  n = x.shape[0]
  l = np.eye(n)
  u = x.copy()
  for k in range(n-1):
    for i in range (k+1, n):
      factor = u[i][k]/u[k][k]
      l[i,k]= factor
      for j in range(k,n):
        u[i][j] -= factor*u[k][j]
  return(l,u)
  

In [24]:
def LU_solve(l,u,b):
  n = l.shape[0]
  lb = np.hstack((l,b.T))
  for k in range(n-1):
    y = lb[k][n]
    for i in range (k+1,n):
      lb[i][n] -= y*lb[i][k]
  y = np.delete(lb,range(n),1)
  uy = np.hstack((u,y))
  x = np.zeros((n,1))
  for k in range(n-1,0-1,-1):
    x[k] = uy[k][n]/uy[k][k]
    for i in range(k-1,0-1,-1):
      uy[i][n]-= x[k]*uy[i][k]
  return(x)

##__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а)<br> 
$\begin{pmatrix}
1 & 2 & 4\\
2 & 9 & 12\\
3 & 26 & 30
\end{pmatrix}$

$\begin{pmatrix}
1 & 2 & 4\\
0 & 5 & 4\\
0 & 20 & 18
\end{pmatrix}$

$\begin{pmatrix}
1 & 2 & 4\\
0 & 5 & 4\\
0 & 0 & 2
\end{pmatrix}$


$L = \begin{pmatrix}
1 & 0 & 0\\
2 & 1 & 0\\
3 & 4 & 1
\end{pmatrix}$

In [25]:
a = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
l,u = LU_decomp(a)
print(f'Матрица L:\n{l}')

Матрица L:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 4. 1.]]


In [26]:
l@u

array([[ 1.,  2.,  4.],
       [ 2.,  9., 12.],
       [ 3., 26., 30.]])

б)<br> 
$\begin{pmatrix}
1 & 1 & 2 & 4\\
2 & 5 & 8 & 9\\
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 & 2 & 4\\
0 & 3 & 4 & 1\\
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 & 2 & 4\\
0 & 3 & 4 & 1\\
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$

$\begin{pmatrix}
1 & 1 & 2 & 4\\
0 & 3 & 4 & 1\\
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

$L = \begin{pmatrix}
1 & 0 & 0 & 0\\
2 & 1 & 0 & 0\\
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

In [27]:
a = np.array([[1,1,2,4],[2,5,8,9],[3,18,29,18],[4,22,53,33]])
l,u = LU_decomp(a)
print(f'Матрица L:\n{l}')

Матрица L:
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 5. 1. 0.]
 [4. 6. 7. 1.]]


In [28]:
l@u

array([[ 1.,  1.,  2.,  4.],
       [ 2.,  5.,  8.,  9.],
       [ 3., 18., 29., 18.],
       [ 4., 22., 53., 33.]])

##__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$\begin{pmatrix}
2 & 1 & 3\\
11 & 7 & 5\\
9 & 8 & 4
\end{pmatrix}$

$\begin{pmatrix}
2 & 1 & 3\\
0 & 1.5 & -11.5\\
0 & 3.5 & -9.5
\end{pmatrix}$

$U = \begin{pmatrix}
2 & 1 & 3\\
0 & 1.5 & -11.5\\
0 & 0 & \frac{52}{3}
\end{pmatrix}$

$L = \begin{pmatrix}
1 & 0 & 0\\
5.5 & 1 & 0\\
4.5 & \frac{7}{3} & 1
\end{pmatrix}$

$Ly = b\\
\begin{cases}
y_{1} = 1\\
5.5y_{1} + y_{2} = -6\\
4.5y_{1} + \frac{7}{3}y_{2} + y_{3} = -5 
\end{cases} \Rightarrow 
\begin{cases}
y_{1} = 1\\
y_{2} = -11.5\\
y_{3} = -5 -4.5 + \frac{161}{6} 
\end{cases} ⇒
\begin{cases}
y_{1} = 1\\
y_{2} = -11.5\\
y_{3} = \frac{52}{3} 
\end{cases}$

$Ux = y\\
\begin{cases}
2x_{1} + x_{2} + 3x_{3} = 1\\
x_{2} - 11.5x{3} = -11.5\\
\frac{52}{3}x_{3} = \frac{52}{3}
\end{cases} \Rightarrow
\begin{cases}
x_{1} = -1\\
x_{2} = 0\\
x_{3} = 1
\end{cases}$



In [34]:
a = np.array([[2,1,3],[11,7,5],[9,8,4]], float)
b = np.array([[1,-6,-5]])

In [30]:
lu, piv = linalg.lu_factor(a)
x = linalg.lu_solve((lu,piv),b.T)
x

array([[-1.],
       [ 0.],
       [ 1.]])

In [35]:
l,u = LU_decomp(a)
print(f'U = \n{u};\nL = \n{l}')

U = 
[[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]];
L = 
[[1.         0.         0.        ]
 [5.5        1.         0.        ]
 [4.5        2.33333333 1.        ]]


In [39]:
x = LU_solve(l,u,b)
print(f'x1 = {x[0]};\nx2 = {x[1]};\nx3 = {x[2]}')

x1 = [-1.];
x2 = [0.];
x3 = [1.]


##__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$


$\begin{pmatrix}
81 & -45 & 45\\
-45 & 50 & -15\\
45 & -15 & 38
\end{pmatrix}$

$l_{11} = \sqrt{a_{11}} = \sqrt{81} = 9\\
l_{21} = \frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5\\
l_{31} = \frac{a_{31}}{l_{11}} = \frac{45}{9} = 5\\
l_{22} = \sqrt{a_{22}-l_{21}^2} = \sqrt{50 - 25} = 5\\
l_{32} = \frac{1}{l_{22}}(a_{32} - l_{21}l_{31}) = \frac{1}{5}(-15 - (-5)\cdot5) = 2\\
l_{33} = \sqrt{a_{33}-l_{31}^2-l_{32^2}} = \sqrt{38 - 25 - 4} = 3
$

$L =\begin{pmatrix}
9 & 0 & 0\\
-5 & 5 & 0\\
5 & 2 & 3
\end{pmatrix}$

$L^T =\begin{pmatrix}
9 & -5 & 5\\
0 & 5 & 2\\
0 & 0 & 3
\end{pmatrix}$

$Ly = b\\
\begin{cases}
9y_{1} = 531\\
-5y_{1} + 5y_{2} = -460\\
5y_{1} + 2y_{2} + 3y_{3} = 193 
\end{cases} ⇒
\begin{cases}
y_{1} = 59\\
5y_{2} = -460 + 295\\
2y_{2} + 3y_{3} = 193 - 295
\end{cases} \Rightarrow
\begin{cases}
y_{1} = 59\\
y_{2} = -33\\
y_{3} = -12
\end{cases}$

$L^Tx = y\\
\begin{cases}
9x_{1} - 5x_{2} + 5x_{3} = 59\\
5x_{2} + 2x_{3} = -33\\
3x_{3} = -12
\end{cases}⇒
\begin{cases}
9x_{1} - 5x_{2} = 59 - 25\\
5x_{2} = -33 + 8\\
x_{3} = -4
\end{cases}⇒
\begin{cases}
x_{1} = 6\\
x_{2} = -5\\
x_{3} = -4
\end{cases}$

In [40]:
a = np.array([[81,-45,45],[-45,50,-15],[45,-15,38]], float)
b = np.array([[531,-460,193]])
L = np.linalg.cholesky(a)
L

array([[ 9.,  0.,  0.],
       [-5.,  5.,  0.],
       [ 5.,  2.,  3.]])

In [42]:
c, low = linalg.cho_factor(a)
x = linalg.cho_solve((c, low), b.T)
print(f'x1 = {x[0]};\nx2 = {x[1]};\nx3 = {x[2]}')

x1 = [6.];
x2 = [-5.];
x3 = [-4.]
