<a href="https://colab.research.google.com/github/alina-bogdanovskaya/Linear_Algebra_Feb2022/blob/lesson2/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import numpy as np

##__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$.

Произведение матриц $AB$ не определено, поскольку число столбцов матрицы $A$ не равно числу строк матрицы $B$.
 
Произведение матриц $BA$ не определено, поскольку число столбцов матрицы $B$ не равно числу строк матрицы $A$.

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$.

Найти произведение матриц $AB$ возможно, результирующая матрица будет иметь размер $2\times 3$.

Произведение матриц $BA$ не определено, поскольку число столбцов матрицы $B$ не равно числу строк матрицы $A$.

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$.

Найти произведение матриц $AB$ возможно, результирующая матрица будет иметь размер $8\times 8$.

Найти произведение матриц $BA$ возможно, результирующая матрица будет иметь размер $3\times 3$.

   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Поскольку обе матрицы квадратные и их размеры совпадают, оба произведени определены. В обоих случаях получим квадратную результирующую матрицу $4\times 4$.

##__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [70]:
def matrices_mult(a,b):
  if len(a) < 1 or len(b) < 1:
    raise ValueError('not a matrix')
  m_a,n_a = a.shape
  m_b,n_b = b.shape
  if n_a != m_b:
    raise ValueError('not equal dimensions')
  c = np.zeros((m_a,n_b))
  for i in range(m_a):
    for j in range(n_b):
      for k in range(n_a):
        c[i][j] += a[i][k]*b[k][j]
  return(c)

##__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$ A + B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$


$ A \cdot B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5\\ 
3 \cdot4 + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$


$ B \cdot A = \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4 \cdot 1 + (-1) \cdot 3 & 4 \cdot (-2) + (-1) \cdot 0\\ 
0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 5 \cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$


In [71]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A:\n {a}')
print(f'Матрица B:\n {b}')

Матрица A:
 [[ 1 -2]
 [ 3  0]]
Матрица B:
 [[ 4 -1]
 [ 0  5]]


In [72]:
print(f'A + B =\n {a+b}')

A + B =
 [[ 5 -3]
 [ 3  5]]


In [73]:
print(f'A * B =\n{a@b}')

A * B =
[[  4 -11]
 [ 12  -3]]


In [74]:
matrices_mult(a,b)

array([[  4., -11.],
       [ 12.,  -3.]])

In [75]:
print(f'B * A =\n{b@a}')

B * A =
[[ 1 -8]
 [15  0]]


In [76]:
matrices_mult(b,a)

array([[ 1., -8.],
       [15.,  0.]])

##__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$ 3 \cdot \begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix} - 
2 \cdot \begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix} +
4 \cdot \begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 & 21\\
9 & -18
\end{pmatrix} -
\begin{pmatrix}
0 & 10\\
4 & -2
\end{pmatrix} +
\begin{pmatrix}
8 & -16\\
4 & 4
\end{pmatrix} = 
\begin{pmatrix}
3 & 11\\
5 & -16
\end{pmatrix} +
\begin{pmatrix}
8 & -16\\
4 & 4
\end{pmatrix} =
\begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix} $

In [77]:
a = np.array([[1,7],[3,-6]])
b = np.array([[0,5],[2,-1]])
c = np.array([[2,-4],[1,1]])

print(f'Матрица A:\n {a}')
print(f'Матрица B:\n {b}')
print(f'Матрица C:\n {c}')

Матрица A:
 [[ 1  7]
 [ 3 -6]]
Матрица B:
 [[ 0  5]
 [ 2 -1]]
Матрица C:
 [[ 2 -4]
 [ 1  1]]


In [78]:
print(f'3A - 2B + 4C =\n {3*a-2*b+4*c}')

3A - 2B + 4C =
 [[ 11  -5]
 [  9 -12]]


##__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 &3
\end{pmatrix}$

$\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}=\begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3\\ 
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3\\ 
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4 + 5\cdot5 +2\cdot2 & 4\cdot1 + 5\cdot(-2) + 2\cdot3\\
1\cdot4 + (-2)\cdot5 + 3\cdot3 & 1\cdot1 + (-2)\cdot(-2) + 3\cdot3 
\end{pmatrix} = \begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}$

In [79]:
a = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица А: \n{a}')
print(f'Матрица А^T: \n{a.T}')

Матрица А: 
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица А^T: 
[[ 4  5  2]
 [ 1 -2  3]]


In [80]:
print(f'A*A^T = \n{a@a.T}')

A*A^T = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [81]:
matrices_mult(a,a.T)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [82]:
print(f'A^T*A = \n{a.T@a}')

A^T*A = 
[[45  0]
 [ 0 14]]


In [83]:
matrices_mult(a.T,a)

array([[45.,  0.],
       [ 0., 14.]])

##__1.__ Вычислить определитель:

   a) $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = 
sin^2 x + cos^2 x = 1$

   б) $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 
4 \cdot 5 \cdot 9 = 180 $

In [84]:
a = np.array([[4,2,3],[0,5,1], [0,0,9]])
np.linalg.det(a)

180.0

   в) $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 
\begin{vmatrix}
5 & 6\\
8 & 9
\end{vmatrix} - 
2 \cdot 
\begin{vmatrix}
4 & 6\\
7 & 9
\end{vmatrix} +
3 \cdot 
\begin{vmatrix}
4 & 5\\
7 & 8
\end{vmatrix} = \\ 
= (45 - 48) - 2 \cdot (36 - 42) + 3 \cdot (32 - 35) = 
45 - 48 - 72 + 84 + 96 - 105 = 0 $

In [85]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(a)

0.0

##__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = 16$;
    
   б) $det(A^{T}) = 4$;
    
   в) $det(2A) = 4 \cdot 2^n$.

##__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Первая и вторая строки матрицы линейно зависимы (множитель пропорциональности -2). Согласно свойству 6, определитель такой матрицы равен нулю. По определению: матрица называется вырожденной, если ее определитель равен нулю. Следовательно, данная матрица вырожденная. 

##__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Третья строка является суммой первых двух. Первая и вторая строки линейно независимы, следовательно ранг матрицы равен 2. 

In [90]:
a = np.array([[1,2,3],[1,1,1],[2,3,4]])
print(f'Ранг = {np.linalg.matrix_rank(a)}')

Ранг = 2


In [88]:
n = a.shape[1]

for k in range(n-1):
    for i in range (k+1, n):
      factor = a[i][k]/a[k][k]
      for j in range(k,n):
        a[i][j] -= factor*a[k][j]
print(a)

[[ 1  2  3]
 [ 0 -1 -2]
 [ 0  0  0]]


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Третья строка является суммой первых двух, ее можно отбросить:

$\begin{pmatrix}
0 & 0 & 2 & 1\\
0 & 0 & 2 & 2\\
2 & 3 & 5 & 6 
\end{pmatrix}$

Поменяем местами вторую и третью строки, затем перенесем последний столбец в начало:

$\begin{pmatrix}
1 & 0 & 0 & 2\\
6 & 2 & 3 & 5\\
2 & 0 & 0 & 2 
\end{pmatrix}$

Вычтем первую строку из второй и третьей, умножив ее на 6 и 2 соответственно:

$\begin{pmatrix}
1 & 0 & 0 & 2\\
0 & 2 & 3 & -7\\
0 & 0 & 0 & -2 
\end{pmatrix}$

Ранг матрицы равен 3.


In [91]:
a = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]], float)
print(f'Ранг = {np.linalg.matrix_rank(a)}')

Ранг = 3
